### ISSUE TITLE
backend/transpiler/tempOutput/Program.cs: Provide useful commit messages and class names

### ISSUE THREAD

**Issue by schramls** [YanniAlshoufiHTL/.mohay#11]
![image](https://github.com/YanniAlshoufiHTL/.mohay/assets/72865956/21765c14-feb8-40df-9ec8-e8a59bc757e0)

'well fuck' is not a suitable commit message
'ZuWild' is not a suitable class name, not even for C# classes!

**Comment by MoritzBernhofer** [comment]
This is completely my fault (Moritz Bernhofer). It will not happen again (commit). And the Class name will be changed.
