### ISSUE TITLE
backend/analyzer /analyzer.js: Don't use switch(true)

### ISSUE THREAD

**Issue by schramls** [YanniAlshoufiHTL/.mohay#9]
Phu, didn't even know that this would work:

switch (true) {
        case line.startsWith("."):
            checkForVariable(line, row);
            break;

Better use if / else if cascades

Btw: There is very similar code in two functions (validate(line, row) and checkForVariable(line, row))

**Comment by MoritzBernhofer** [comment]
The code mentioned is old (unused) and will be deleted after merging all the major branches.
Yes switch true works (kinda), but is very inefficient.
